from datetime import UTC, date, datetime, time, timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.core.security import hash_password
from app.db.base import Base
from app.db.models.appointment import Appointment, AppointmentStatus, AppointmentType
from app.db.models.doctor import DoctorProfile
from app.db.models.encounter import Encounter, EncounterKind
from app.db.models.notification import Notification, NotificationType
from app.db.models.patient import PatientProfile
from app.db.models.user import User, UserRole


def seed_database(db: Session) -> None:
    settings = get_settings()
    if not settings.seed_demo_data:
        return
    if db.scalar(select(User.id).limit(1)):
        return

    today = date.today()
    tomorrow = today + timedelta(days=1)
    yesterday = today - timedelta(days=1)
    two_days_ago = today - timedelta(days=2)
    now = datetime.now(UTC)

    users = [
        User(
            id="u-admin",
            email="admin@saludpe.pe",
            full_name="Administrador SaludPe",
            role=UserRole.ADMIN,
            password_hash=hash_password("SaludPe123!"),
            notification_preferences=User.DEFAULT_NOTIFICATION_PREFERENCES,
        ),
        User(
            id="u-doctor-1",
            email="medico@saludpe.pe",
            full_name="Dra. María Elena Quispe",
            role=UserRole.DOCTOR,
            password_hash=hash_password("SaludPe123!"),
            notification_preferences=User.DEFAULT_NOTIFICATION_PREFERENCES,
        ),
        User(
            id="u-patient-1",
            email="paciente@saludpe.pe",
            full_name="Juan Pérez Sánchez",
            role=UserRole.PATIENT,
            password_hash=hash_password("SaludPe123!"),
            notification_preferences=User.DEFAULT_NOTIFICATION_PREFERENCES,
        ),
    ]
    db.add_all(users)

    doctors = [
        DoctorProfile(
            id="1",
            user_id="u-doctor-1",
            name="Dra. María Elena Quispe",
            specialty="Cardiología",
            rating=4.9,
            reviews=234,
            price=120,
            location="San Isidro, Lima",
            distance="2.3 km",
            available=True,
            modalities=["presencial", "telemedicina"],
            insurances=["Rímac", "Pacífico"],
            languages=["Español", "Quechua"],
            bio="Cardióloga con 15 años de experiencia en el Instituto Nacional Cardiovascular.",
            experience=15,
            phone="+51 999 888 777",
            avatar="",
        ),
        DoctorProfile(
            id="2",
            name="Dr. Carlos Huamán Rojas",
            specialty="Medicina General",
            rating=4.7,
            reviews=189,
            price=60,
            location="Miraflores, Lima",
            distance="1.1 km",
            available=True,
            modalities=["presencial", "telemedicina"],
            insurances=["Rímac", "Mapfre", "SIS"],
            languages=["Español"],
            bio="Médico general dedicado a la atención primaria con enfoque preventivo.",
            experience=10,
            phone="+51 944 111 222",
            avatar="",
        ),
        DoctorProfile(
            id="3",
            name="Dra. Lucía Fernández Paredes",
            specialty="Dermatología",
            rating=4.8,
            reviews=312,
            price=100,
            location="Surco, Lima",
            distance="4.5 km",
            available=False,
            modalities=["presencial"],
            insurances=["Pacífico", "La Positiva"],
            languages=["Español", "Inglés"],
            bio="Dermatóloga certificada con subespecialidad en dermatología estética y oncológica.",
            experience=12,
            phone="+51 955 222 333",
            avatar="",
        ),
        DoctorProfile(
            id="4",
            name="Dr. Andrés Villanueva Soto",
            specialty="Pediatría",
            rating=4.9,
            reviews=421,
            price=80,
            location="Jesús María, Lima",
            distance="3.0 km",
            available=True,
            modalities=["presencial", "telemedicina"],
            insurances=["Rímac", "Pacífico", "Mapfre"],
            languages=["Español", "Inglés"],
            bio="Pediatra con amplia experiencia en neonatología y desarrollo infantil.",
            experience=18,
            phone="+51 966 333 444",
            avatar="",
        ),
        DoctorProfile(
            id="5",
            name="Dra. Rosa Mendoza Chávez",
            specialty="Ginecología",
            rating=4.6,
            reviews=156,
            price=110,
            location="San Borja, Lima",
            distance="5.2 km",
            available=True,
            modalities=["telemedicina"],
            insurances=["Rímac", "SIS"],
            languages=["Español", "Quechua", "Inglés"],
            bio="Ginecóloga obstetra especializada en salud reproductiva y embarazo de alto riesgo.",
            experience=20,
            phone="+51 977 444 555",
            avatar="",
        ),
        DoctorProfile(
            id="6",
            name="Dr. Felipe Torres Luna",
            specialty="Neurología",
            rating=4.8,
            reviews=98,
            price=150,
            location="La Molina, Lima",
            distance="7.8 km",
            available=True,
            modalities=["presencial"],
            insurances=["Pacífico", "Mapfre"],
            languages=["Español", "Inglés"],
            bio="Neurólogo con experiencia en epilepsia y trastornos del sueño.",
            experience=14,
            phone="+51 988 555 666",
            avatar="",
        ),
    ]
    db.add_all(doctors)

    patients = [
        PatientProfile(
            id="p1",
            user_id="u-patient-1",
            name="Juan Pérez Sánchez",
            age=45,
            gender="M",
            phone="+51 987 654 321",
            email="paciente@saludpe.pe",
            insurance="Rímac",
            last_visit="2026-02-15",
            avatar="",
            blood_type="O+",
            conditions=["Hipertensión", "Diabetes tipo 2"],
            allergies=["Penicilina"],
            emergency_contact_name="María Sánchez",
            emergency_contact_phone="+51 987 111 222",
            emergency_contact_relationship="Esposa",
        ),
        PatientProfile(
            id="p2",
            name="Ana María López",
            age=32,
            gender="F",
            phone="+51 912 345 678",
            email="ana.lopez@email.com",
            insurance="Pacífico",
            last_visit="2026-02-28",
            avatar="",
            blood_type="A+",
            conditions=["Asma"],
            allergies=[],
            emergency_contact_name="Carlos López",
            emergency_contact_phone="+51 912 000 111",
            emergency_contact_relationship="Hermano",
        ),
        PatientProfile(
            id="p3",
            name="Roberto García Flores",
            age=58,
            gender="M",
            phone="+51 945 678 123",
            email="roberto.garcia@email.com",
            insurance="Mapfre",
            last_visit="2026-01-20",
            avatar="",
            blood_type="B+",
            conditions=["Arritmia cardíaca", "Colesterol alto"],
            allergies=["Sulfonamidas", "Ibuprofeno"],
            emergency_contact_name="Elena García",
            emergency_contact_phone="+51 945 000 111",
            emergency_contact_relationship="Esposa",
        ),
        PatientProfile(
            id="p4",
            name="Carmen Ríos Vega",
            age=27,
            gender="F",
            phone="+51 976 543 210",
            email="carmen.rios@email.com",
            insurance="SIS",
            last_visit="2026-03-01",
            avatar="",
            blood_type="AB+",
            conditions=[],
            allergies=[],
        ),
        PatientProfile(
            id="p5",
            name="Luis Fernando Mendoza",
            age=63,
            gender="M",
            phone="+51 934 567 890",
            email="luis.mendoza@email.com",
            insurance="La Positiva",
            last_visit="2026-02-10",
            avatar="",
            blood_type="A-",
            conditions=["EPOC", "Hipertensión"],
            allergies=["Aspirina"],
            emergency_contact_name="Rosa Mendoza",
            emergency_contact_phone="+51 934 000 111",
            emergency_contact_relationship="Hija",
        ),
        PatientProfile(
            id="p6",
            name="Sofía Castillo Torres",
            age=19,
            gender="F",
            phone="+51 923 456 789",
            email="sofia.castillo@email.com",
            insurance="Rímac",
            last_visit="2026-02-25",
            avatar="",
            blood_type="O-",
            conditions=["Dermatitis atópica"],
            allergies=["Látex"],
        ),
    ]
    db.add_all(patients)

    appointments = [
        Appointment(
            id="a1",
            doctor_id="1",
            patient_id="p1",
            date=today,
            time=time(8, 0),
            duration=30,
            type=AppointmentType.IN_PERSON,
            status=AppointmentStatus.CONFIRMED,
            reason="Control de presión arterial",
            notes="Traer resultados de laboratorio recientes",
        ),
        Appointment(
            id="a2",
            doctor_id="1",
            patient_id="p2",
            date=today,
            time=time(8, 30),
            duration=30,
            type=AppointmentType.TELEMEDICINE,
            status=AppointmentStatus.CONFIRMED,
            reason="Revisión de tratamiento para asma",
        ),
        Appointment(
            id="a3",
            doctor_id="1",
            patient_id="p4",
            date=today,
            time=time(9, 0),
            duration=30,
            type=AppointmentType.IN_PERSON,
            status=AppointmentStatus.WAITING,
            reason="Consulta general - dolor de cabeza frecuente",
        ),
        Appointment(
            id="a4",
            doctor_id="1",
            patient_id="p3",
            date=today,
            time=time(9, 30),
            duration=45,
            type=AppointmentType.IN_PERSON,
            status=AppointmentStatus.CONFIRMED,
            reason="Evaluación cardiológica de seguimiento",
            notes="Paciente con antecedente de arritmia",
        ),
        Appointment(
            id="a5",
            doctor_id="1",
            patient_id="p5",
            date=today,
            time=time(10, 30),
            duration=30,
            type=AppointmentType.TELEMEDICINE,
            status=AppointmentStatus.CANCELLED,
            reason="Control de EPOC",
        ),
        Appointment(
            id="a6",
            doctor_id="1",
            patient_id="p6",
            date=today,
            time=time(11, 0),
            duration=30,
            type=AppointmentType.IN_PERSON,
            status=AppointmentStatus.WAITING,
            reason="Brote de dermatitis",
        ),
        Appointment(
            id="a7",
            doctor_id="1",
            patient_id="p1",
            date=tomorrow,
            time=time(9, 0),
            duration=30,
            type=AppointmentType.IN_PERSON,
            status=AppointmentStatus.CONFIRMED,
            reason="Resultados de laboratorio",
        ),
        Appointment(
            id="a8",
            doctor_id="1",
            patient_id="p2",
            date=tomorrow,
            time=time(10, 0),
            duration=30,
            type=AppointmentType.TELEMEDICINE,
            status=AppointmentStatus.CONFIRMED,
            reason="Seguimiento respiratorio",
        ),
        Appointment(
            id="a9",
            doctor_id="1",
            patient_id="p3",
            date=yesterday,
            time=time(8, 0),
            duration=45,
            type=AppointmentType.IN_PERSON,
            status=AppointmentStatus.COMPLETED,
            reason="Electrocardiograma de control",
        ),
        Appointment(
            id="a10",
            doctor_id="1",
            patient_id="p4",
            date=two_days_ago,
            time=time(11, 0),
            duration=30,
            type=AppointmentType.TELEMEDICINE,
            status=AppointmentStatus.COMPLETED,
            reason="Primera consulta - migrañas",
        ),
    ]
    db.add_all(appointments)

    encounters = [
        Encounter(
            id="enc-p1-consult-1",
            patient_id="p1",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.CONSULTATION,
            occurred_on=date(2026, 2, 15),
            actor_name="Dr. Carlos Mendoza",
            specialty="Cardiología",
            payload={
                "diagnosis": "Hipertensión arterial leve",
                "diagnosis_status": "Activo",
                "prescriptions": [
                    {
                        "medication": "Losartán 50mg",
                        "dosage": "1 tableta",
                        "frequency": "1 vez al día",
                        "duration": "3 meses",
                    },
                    {
                        "medication": "Amlodipino 5mg",
                        "dosage": "1 tableta",
                        "frequency": "1 vez al día",
                        "duration": "3 meses",
                    },
                ],
                "recommendations": ["Reducir consumo de sal", "Caminar 30 minutos al día"],
                "lab_orders": ["Hemograma completo", "Perfil lipídico"],
                "notes": "Control en 1 mes con resultados de laboratorio.",
            },
        ),
        Encounter(
            id="enc-p1-lab-1",
            patient_id="p1",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.LAB,
            occurred_on=date(2026, 2, 10),
            actor_name="Laboratorio Roe",
            specialty="Cardiología",
            payload={
                "ordered_by": "Dr. Carlos Mendoza",
                "lab_results": [
                    {
                        "test": "Colesterol LDL",
                        "result": "165",
                        "reference_range": "< 130",
                        "unit": "mg/dL",
                        "status": "Anormal",
                    },
                    {
                        "test": "Glucosa en ayunas",
                        "result": "92",
                        "reference_range": "70 – 100",
                        "unit": "mg/dL",
                        "status": "Normal",
                    },
                ],
            },
        ),
        Encounter(
            id="enc-p1-lab-2",
            patient_id="p1",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.LAB,
            occurred_on=date(2026, 3, 5),
            actor_name="Laboratorio Suiza Lab",
            specialty="Cardiología",
            payload={
                "ordered_by": "Dr. Carlos Mendoza",
                "lab_results": [
                    {
                        "test": "Colesterol LDL",
                        "result": "138",
                        "reference_range": "< 130",
                        "unit": "mg/dL",
                        "status": "Anormal",
                    },
                    {
                        "test": "Hemoglobina glicosilada",
                        "result": "5.4",
                        "reference_range": "< 5.7",
                        "unit": "%",
                        "status": "Normal",
                    },
                ],
            },
        ),
        Encounter(
            id="enc-p2-consult-1",
            patient_id="p2",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.CONSULTATION,
            occurred_on=date(2026, 1, 3),
            actor_name="Dra. Ana Gutiérrez",
            specialty="Medicina General",
            payload={
                "diagnosis": "Rinitis alérgica estacional",
                "diagnosis_status": "Resuelto",
                "prescriptions": [
                    {
                        "medication": "Loratadina 10mg",
                        "dosage": "1 tableta",
                        "frequency": "1 vez al día",
                        "duration": "14 días",
                    },
                ],
                "recommendations": ["Evitar exposición a polvo y polen"],
                "lab_orders": [],
                "notes": "Si los síntomas persisten después de 2 semanas, volver para evaluación.",
            },
        ),
        Encounter(
            id="enc-p3-consult-1",
            patient_id="p3",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.CONSULTATION,
            occurred_on=date(2025, 11, 15),
            actor_name="Dr. Roberto Sánchez",
            specialty="Gastroenterología",
            payload={
                "diagnosis": "Gastritis crónica",
                "diagnosis_status": "Activo",
                "prescriptions": [
                    {
                        "medication": "Omeprazol 20mg",
                        "dosage": "1 cápsula",
                        "frequency": "1 vez al día (en ayunas)",
                        "duration": "2 meses",
                    }
                ],
                "recommendations": [
                    "Evitar café, alcohol y gaseosas",
                    "Comer en horarios regulares",
                ],
                "lab_orders": ["Test de Helicobacter pylori"],
                "notes": "Evaluar resultado del test de H. pylori.",
            },
        ),
        Encounter(
            id="enc-p4-surgery-1",
            patient_id="p4",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.SURGERY,
            occurred_on=date(2025, 12, 20),
            actor_name="Dr. Javier Morales",
            specialty="Cirugía General",
            payload={
                "hospital": "Clínica San Felipe",
                "procedure": "Apendicectomía laparoscópica",
                "procedure_type": "Emergencia",
                "anesthesia_type": "Anestesia general",
                "duration": "45 minutos",
                "pre_op_diagnosis": "Apendicitis aguda",
                "post_op_diagnosis": "Apendicitis aguda no complicada",
                "findings": ["Apéndice inflamado sin perforación"],
                "complications": [],
                "post_op_instructions": ["Reposo relativo por 7 días"],
                "prescriptions": [],
                "follow_up": "Control en 10 días para retiro de puntos",
                "notes": "Paciente toleró bien el procedimiento.",
            },
        ),
        Encounter(
            id="enc-p5-surgery-1",
            patient_id="p5",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.SURGERY,
            occurred_on=date(2025, 8, 15),
            actor_name="Dra. Patricia Flores",
            specialty="Cirugía General",
            payload={
                "hospital": "Hospital Nacional Arzobispo Loayza",
                "procedure": "Colecistectomía laparoscópica",
                "procedure_type": "Electiva",
                "anesthesia_type": "Anestesia general",
                "duration": "1 hora 10 minutos",
                "pre_op_diagnosis": "Colelitiasis sintomática",
                "post_op_diagnosis": "Colelitiasis múltiple, vesícula con paredes engrosadas",
                "findings": [
                    "Vesícula biliar con paredes engrosadas y múltiples cálculos",
                    "Vía biliar principal sin dilatación",
                ],
                "complications": [],
                "post_op_instructions": [
                    "Dieta baja en grasas por 4 semanas",
                    "Reposo relativo por 10 días",
                ],
                "prescriptions": [
                    {
                        "medication": "Tramadol 50mg",
                        "dosage": "1 cápsula",
                        "frequency": "Cada 8 horas (si dolor)",
                        "duration": "5 días",
                    }
                ],
                "follow_up": "Control en 2 semanas con resultados de anatomía patológica",
                "notes": "Procedimiento sin complicaciones.",
            },
        ),
        Encounter(
            id="enc-p6-surgery-1",
            patient_id="p6",
            doctor_id="1",
            appointment_id=None,
            kind=EncounterKind.SURGERY,
            occurred_on=date(2025, 6, 2),
            actor_name="Dr. Ricardo Vega",
            specialty="Traumatología y Ortopedia",
            payload={
                "hospital": "Clínica Ricardo Palma",
                "procedure": "Artroscopia de rodilla derecha",
                "procedure_type": "Ambulatoria",
                "anesthesia_type": "Anestesia raquídea",
                "duration": "35 minutos",
                "pre_op_diagnosis": "Lesión de menisco medial, rodilla derecha",
                "post_op_diagnosis": "Rotura del cuerno posterior del menisco medial",
                "findings": [
                    "Rotura compleja del cuerno posterior del menisco medial",
                    "Se realizó meniscectomía parcial",
                ],
                "complications": [],
                "post_op_instructions": [
                    "Uso de muletas por 1 semana",
                    "Iniciar fisioterapia a partir del día 5",
                ],
                "prescriptions": [
                    {
                        "medication": "Celecoxib 200mg",
                        "dosage": "1 cápsula",
                        "frequency": "Cada 12 horas",
                        "duration": "7 días",
                    }
                ],
                "follow_up": "Control en 1 semana con protocolo de rehabilitación",
                "notes": "Procedimiento ambulatorio sin incidentes.",
            },
        ),
    ]
    db.add_all(encounters)

    notifications = [
        Notification(
            id="n1",
            user_id="u-doctor-1",
            type=NotificationType.APPOINTMENT,
            title="Nueva cita agendada",
            message="Juan Pérez agendó una consulta para hoy a las 10:00.",
            link="/doctor/portal/agenda",
            read=False,
            created_at=now - timedelta(minutes=12),
        ),
        Notification(
            id="n2",
            user_id="u-doctor-1",
            type=NotificationType.REMINDER,
            title="Consulta en 30 minutos",
            message="Tienes una consulta con Ana María López a las 15:00.",
            link="/doctor/portal/agenda",
            read=False,
            created_at=now - timedelta(minutes=28),
        ),
        Notification(
            id="n3",
            user_id="u-doctor-1",
            type=NotificationType.CANCELLATION,
            title="Cita cancelada",
            message="Luis Fernando Mendoza canceló su cita próxima.",
            link="/doctor/portal/agenda",
            read=False,
            created_at=now - timedelta(hours=2),
        ),
        Notification(
            id="n4",
            user_id="u-doctor-1",
            type=NotificationType.SYSTEM,
            title="Nueva funcionalidad disponible",
            message="Ahora puedes compartir recetas directamente por WhatsApp.",
            link="/doctor/portal/configuracion",
            read=True,
            created_at=now - timedelta(days=1),
        ),
    ]
    db.add_all(notifications)
    db.commit()


def init_database(engine) -> None:
    Base.metadata.create_all(bind=engine)
    with Session(bind=engine) as db:
        seed_database(db)
